[package]
name = "cargo_ntfy"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking", "rustls-tls"] }
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
openssl = { version = "0.10", features = ["vendored"] }
